### ISSUE TITLE
public key authentication config examples in Client authentication section wrong?

### ISSUE THREAD

**Issue by abraxxa** [stribika/stribika.github.io#12]
The sshd and ssh config examples have 'PasswordAuthentication no' like in the examples above about disabling password authentication.
I guess it should read 'RSAAuthentication yes'.

**Comment by stribika** [comment]
RSAAuthentication only affects the v1 protocol which should always be disabled. PubkeyAuthentication is yes by default but I guess I can add it.

**Comment by abraxxa** [comment]
Ah, that's why I didn't find it in my config!
Then PubKeyAuthentication is what I meant.

**Comment by stribika** [comment]
Should be good now.
