### ISSUE TITLE
putty and winscp use weak key exchange

### ISSUE THREAD

**Issue by jumanjiman** [stribika/stribika.github.io#15]
it might be nice to add a warning in the secure-secure-shell article about the limitations of putty

tl;dr putty only allows diffie-hellman-group1 or diffie-hellman-group14 key exchange according to http://the.earth.li/~sgtatham/putty/0.63/htmldoc/Chapter4.html#config-ssh-kex (linked from http://www.chiark.greenend.org.uk/~sgtatham/putty/docs.html)

my users report that putty appears to hang on connection with no useful error/troubleshooting messages.

workaround: i've advised my users to use chrome browser and the [ssh extension](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo) or cygwin

ref https://github.com/jumanjihouse/wormhole/issues/51

**Comment by stribika-rdonly** [comment]
diffie-hellman-group-exchange-sha256 is available (or will be soon) in the latest PuTTY: http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=blob_plain;f=sshdh.c;hb=HEAD
I don't know about winscp.

**Comment by jumanjiman** [comment]
thx

**Comment by stribika** [comment]
Does it really work? I can't test this so if you have anything to add, [you can do so](https://github.com/stribika/stribika.github.io/wiki/Secure-Secure-Shell).

**Comment by jumanjiman** [comment]
done! https://github.com/stribika/stribika.github.io/wiki/Secure-Secure-Shell

**Comment by shtrom** [comment]
Hum, this still doesn't seem to work with PuTTY 0.64 (or, at least, it doesn't connect)

**Comment by shtrom** [comment]
Here's what my Secure SSH server says when Putty 0.64 rev 2 (from PortableApps) tries to connect.

    Apr 22 14:59:01 bla sshd[7746]: fatal: no matching mac found: client hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5 server hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com [preauth]

**Comment by shtrom** [comment]
‎‎    shtrom‎: putty only supports hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5; no EtM
    shtrom‎: which one should I enable that is the least bad?
‎‎    shtrom‎: hmac-sha2-256, I guess
‎    XX‎: It probably does not matter, they're all vulnerable :D
‎    XX‎: yeah, go for that one

Well, I'll do that...
