### ISSUE TITLE
Should ChallengeResponseAuthentication be set to 'no' as well?

### ISSUE THREAD

**Issue by jasonkarns** [stribika/stribika.github.io#17]
Aren't ChallengeResponseAuthentication and PasswordAuthentication usually set in tandem (both enabled or both disabled)? If recommending to disable PasswordAuthentication, shouldn't ChallengeResponseAuthentication also be disabled? (unless using PAM with Google Authenticator)

**Comment by stribika** [comment]
Yeah, unless you actually configured PAM for something other than passwords. The way it is now, ssh asks me for a password if I delete the client keys.
