### ISSUE TITLE
Debian/Ubuntu: Consider setting ServerKeyBits 768 to 1024

### ISSUE THREAD

**Issue by fsteinel** [stribika/stribika.github.io#18]
I have a old Debian squeeze running and in sshd_config ServerKeyBits is set to 768 instead of the Upstream default 1024.

Ubuntu: https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1244272
Debain: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=727622
Source: https://scottlinux.com/2013/11/01/debian-and-ubuntu-linux-set-openssh-severkeybits-to-1024/

**Comment by stribika** [comment]
ServerKeyBits doesn't matter unless you are using Protocol 1. In which case run, don't walk, to your server and switch to Protocol 2.
