### ISSUE TITLE
Add MACs line for Heroku

### ISSUE THREAD

**Issue by colindean** [stribika/stribika.github.io#22]
Looks like Heroku supports only `hmac-sha1,hmac-md5`.

```
no matching mac found: client hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com server hmac-sha1,hmac-md5
```

**Comment by colindean** [comment]
This works for me:

```
Host heroku.com
  MACs hmac-sha1,hmac-md5
  IdentitiesOnly yes
  KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group1-sha1
```

Not sure if that's as secure as it could be.

**Comment by stribika** [comment]
I added it to the [wiki page](https://github.com/stribika/stribika.github.io/wiki/Secure-Secure-Shell) with the difference of trying literally everything before resorting to these algorithms. Heroku may upgrade its servers later and you could end up using 1024 bit DH because of your own config.

**Comment by colindean** [comment]
:beers: thanks, @stribika, perhaps @changetip will afford you a beer on me.

**Comment by changetip** [comment]
Hi @stribika, @colindean sent you a Bitcoin tip worth a beer (16,391 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/361496)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by stribika** [comment]
Thank you.
