### ISSUE TITLE
OpenSSH dosen't log the source ip for "Unable to negotiate a key exchange method"

### ISSUE THREAD

**Issue by zet4** [stribika/stribika.github.io#24]
Hello, I would like to ask if anyone else is having this issue with OpenSSH?
I am using fail2ban and no ip in logs means I can't ban those crackers.
Not that its a problem, since they can't really do anything with it.
But still this makes a big mess in my logs.

**Comment by stribika** [comment]
If you go all the way and only allow connections from the hidden service, you will see all connections coming from 127.0.0.1 so fail2ban would not work at all. However, it would make your address a lot harder to find and even harder to know that it's *your* address. 

There's no way these skiddies can break public key authentication with an online attack. Disable password authentication, perhaps follow one of the guides for 2 factor authentication and you won't need fail2ban.
