### ISSUE TITLE
Drawing attention to OpenSSH's undocumented fallback with DHGEX

### ISSUE THREAD

**Issue by ameliaikeda** [stribika/stribika.github.io#27]
OpenSSH has a bug in it ([#2302](https://bugzilla.mindrot.org/show_bug.cgi?id=2302)) that automatically falls back to `diffie-hellman-group-14-sha1` when using DHGEX when no moduli params can be found

**Comment by stribika** [comment]
(Sorry, the link didn't load and I can only see various cached versions.) Just group-14 not SHA1, right? And only with empty /etc/ssh/moduli. I'll check this code out to be on the safe side. Thanks!

**Comment by stribika** [comment]
This is what we're talking about, in dh.c:

<code>
DH *
choose_dh(int min, int wantbits, int max)
{
    FILE *f; 
    char line[4096];
    int best, bestcount, which;
    int linenum;
    struct dhgroup dhg;

    if ((f = fopen(_PATH_DH_MODULI, "r")) == NULL &&
        (f = fopen(_PATH_DH_PRIMES, "r")) == NULL) {
        logit("WARNING: %s does not exist, using fixed modulus",
            _PATH_DH_MODULI);
        return (dh_new_group14());
    }   

    linenum = 0;
    best = bestcount = 0;
    while (fgets(line, sizeof(line), f)) {
        linenum++;
        if (!parse_prime(linenum, line, &dhg))
            continue;
        BN_clear_free(dhg.g);
        BN_clear_free(dhg.p);

        if (dhg.size > max || dhg.size < min)
            continue;

        if ((dhg.size > wantbits && dhg.size < best) ||
            (dhg.size > best && best < wantbits)) {
            best = dhg.size;
            bestcount = 0;
        }   
        if (dhg.size == best)
            bestcount++;
    }   
    rewind(f);

    if (bestcount == 0) {
        fclose(f);
        logit("WARNING: no suitable primes in %s", _PATH_DH_PRIMES);
        return (dh_new_group14());
    }   

    linenum = 0;
    which = arc4random_uniform(bestcount);
    while (fgets(line, sizeof(line), f)) {
        if (!parse_prime(linenum, line, &dhg))
            continue;
        if ((dhg.size > max || dhg.size < min) ||
            dhg.size != best ||
            linenum++ != which) {
            BN_clear_free(dhg.g);
            BN_clear_free(dhg.p);
            continue;
        }
        break;
    }
    fclose(f);
    if (linenum != which+1)
        fatal("WARNING: line %d disappeared in %s, giving up",
            which, _PATH_DH_PRIMES);

    return (dh_new_group(dhg.g, dhg.p));
}
</code>

As far as I can tell, the moduli file is not used anywhere else. This is called by kexgex_server, in kexgexs.c. What I get from this is if the moduli file is not readable or empty, the server returns a fixed, 2048 bit prime in the SSH2_MSG_KEX_DH_GEX_GROUP message but it's still diffie-hellman-group-exchange-sha256.

Am I missing something?

**Comment by ameliaikeda** [comment]
Hmm, mindrot seems to be down. If the client and server cannot agree on group exchange params, it will fall back to diffie-hellman-group-14-sha1 (only on openssh <-> openssh). The bug is also on the debian mailing list somewhere, I'll see if I can find it.

**Comment by ameliaikeda** [comment]
Ah, never mind. I thought I'd do some digging, but I assumed it fell back to sha1 with group14, but this seems to not be a *huge* issue.
