### ISSUE TITLE
Strange KEX issue with github via homebrew

### ISSUE THREAD

**Issue by jasonkarns** [stribika/stribika.github.io#36]
I've been successfully following this setup for months, including with extremely frequent github use. However, today I'm experiencing issues with github *but only when executed through homebrew*.

Situation:
```
$ brew install bats --HEAD
==> Cloning https://github.com/sstephenson/bats.git
Cloning into '/Library/Caches/Homebrew/bats--git'...
Unsupported KEX algorithm "curve25519-sha256@libssh.org"
/Users/jasonkarns/.ssh/config line 34: Bad SSH2 KexAlgorithms 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1'.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to download resource "bats"
Failure while executing: git clone --depth 1 --branch master https://github.com/sstephenson/bats.git /Library/Caches/Homebrew/bats--git
```

However, if I remove the `--HEAD` option, homebrew works fine:
```
$ brew install bats
==> Downloading https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/bats-0.4.0.tar.gz
==> ./install.sh /usr/local/Cellar/bats/0.4.0
🍺  /usr/local/Cellar/bats/0.4.0: 10 files, 60K, built in 2 seconds
```

So I tried directly executing the `git clone` command that homebrew is complaining about and it clones just fine.

```
$ git clone --depth 1 --branch master https://github.com/sstephenson/bats.git /Library/Caches/Homebrew/bats--git
Cloning into '/Library/Caches/Homebrew/bats--git'...
remote: Counting objects: 60, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 60 (delta 0), reused 46 (delta 0), pack-reused 0
Receiving objects: 100% (60/60), 23.30 KiB | 0 bytes/s, done.
Checking connectivity... done.
```

Now that it's successfully cloned, invoking homebrew again gives another, more different error:

```
$ brew install bats --HEAD
==> Cloning https://github.com/sstephenson/bats.git
Updating /Library/Caches/Homebrew/bats--git
Unsupported KEX algorithm "curve25519-sha256@libssh.org"
/Users/jasonkarns/.ssh/config line 34: Bad SSH2 KexAlgorithms 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1'.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to download resource "bats"
Failure while executing: git fetch -q origin
```

And, of course, executing `git fetch -q origin` manually from the bats--git repo works fine.

So something is going on with homebrew+github, but I haven't the foggiest idea what it is. Has anyone else experienced this?

**Comment by jasonkarns** [comment]
I posted this here if anyone has any ideas, but as the git commands work fine when executed directly, I believe this is likely a homebrew-specific problem. As such, I've opened a ticket with Homebrew: https://github.com/Homebrew/homebrew/issues/40414

But I'm hoping someone here might have some insight. (btw, I cranked up the SSH loglevel to DEBUG3, but evidently Homebrew is swallowing that output because I don't get any additional logging)

**Comment by justinmayer** [comment]
@jasonkarns: Since you seem to have resolved your non-system-SSH problem in the Homebrew thread, perhaps you'd care to close this issue?

**Comment by jasonkarns** [comment]
yep, thanks!
