### ISSUE TITLE
7.0/7.0p1 removes v00 support.

### ISSUE THREAD

**Issue by DomT4** [stribika/stribika.github.io#39]
```
ssh_config: Bad key types 'ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-ed25519,ssh-rsa'.
```

Per [upstream](http://www.openssh.com/txt/release-7.0) the 7.0 release removes support for the `v00` cert format, and consequently flags that as unrecognised at runtime with a hard exit. Would submit a PR, but don't know if you want to keep the option around for <7.0 OpenSSH versions?

**Comment by jasonkarns** [comment]
@DomT4 thanks for this. i was lost trying to figure out what changed

**Comment by DomT4** [comment]
Fixed by https://github.com/stribika/stribika.github.io/commit/bed0f74f9d251a752690587fa195c7b323ac26ed.
