### ISSUE TITLE
OpenSSH “roaming” vulnerability could leak crypto keys

### ISSUE THREAD

**Issue by serge-stroobandt** [stribika/stribika.github.io#41]
In view of this:
http://www.linuxinsider.com/story/OpenSSH-Flaw-Could-Leak-Crypto-Keys-82991.html

Recommended `/etc/ssh/ssh_config` snippet:

    UseRoaming no

Reference: https://fedoramagazine.org/openssh-vulnerability-expose-private-credentials/

**Comment by stribika** [comment]
This is fixed in 6ac88b2. Thanks.
