### ISSUE TITLE
HostKeyAlgorithms

### ISSUE THREAD

**Issue by Feakster** [stribika/stribika.github.io#45]
I'm currently playing around with your configurations for my servers & have noticed in your setup instructions that you don's specify a `HostKeyAlgorithms` option for the sshd_config file on the server.

My server supports the following host key algorithms:

```shell
ssh -Q key
ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
ssh-rsa-cert-v01@openssh.com
ssh-dss-cert-v01@openssh.com
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
ssh-rsa-cert-v00@openssh.com
ssh-dss-cert-v00@openssh.com
```

However, I cannot SSH in with my current `$HOME/.ssh/config` settings, in which I specify I want to use the `ssh-ed25519-cert-v01@openssh.com` `HostKeyAlgorithm`:

```shell
Host home
    HostName 192.168.1.86
    IdentityFile ~/.ssh/id_ed25519
    UseKeychain yes
    Ciphers chacha20-poly1305@openssh.com
    HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com
    KexAlgorithms curve25519-sha256@libssh.org
    MACs hmac-sha2-512-etm@openssh.com
```

Attempting to SSH in with these settings prompts the response:

```shell
Unable to negotiate with 192.168.1.86 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-ed25519
```

Would specifying the `HostKeyAlgorithms` on the server side help, or am I doing something else wrong?

**Comment by jauderho** [comment]
Try using this instead.

HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519


BTW _ssh -Q_ queries support on the client side not server side
