### ISSUE TITLE
Unable to negotiate a key exchange method

### ISSUE THREAD

**Issue by AllThatIsTheCase** [stribika/stribika.github.io#9]
I currently can't push or pull github after implementing "Secure Secure Shell", getting: "Unable to negotiate a key exchange method"

**Comment by stribika** [comment]
Do you have this uncommented?

<pre><code>Host github.com
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1</code></pre>

Github is weird. I don't even have a special case for it, and it works fine with this: <code>KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256</code>

I've heard that some people need the SHA1 variants <code>diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1</code>. You may want to start enabling the remaining algorithms, starting with the NIST curves in decreasing order of prime size, then if those don't work, group1. If you do this, all the assumptions about downgrade resistance are invalid, and you should enable ciphers & macs one by one until it works, then stick to that.

It just seems like a weird thing for github to do on purpose. I'd love to see an official list of supported algorithms. This *might* even be someone doing downgrade attacks right now. Of course, it could be an accident - a load balancer somewhere with different server configs in the same pool.

**Comment by AllThatIsTheCase** [comment]
Yeah, I had those uncommented, and those two sha1 variants were already in the list; no dice. Is a full list available of the KexAlgorithms and MACs I could work through in order?

**Comment by AllThatIsTheCase** [comment]
I've been told the output of ssh -v -v should be meaningful to those who understand ssh:

ssh -v -v github.com
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: /etc/ssh/ssh_config line 59: Applying options for github.com
debug2: ssh_connect: needpriv 0
debug1: Connecting to github.com [192.30.252.130] port 22.
debug1: Connection established.
debug1: identity file .../.ssh/id_rsa type 1
debug1: identity file .../.ssh/id_rsa-cert type -1
debug1: identity file .../.ssh/id_dsa type 2
debug1: identity file .../.ssh/id_dsa-cert type -1
debug1: identity file .../.ssh/id_ecdsa type -1
debug1: identity file /home/emile/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/emile/.ssh/id_ed25519 type 4
debug1: identity file /home/emile/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-8
debug1: Remote protocol version 2.0, remote software version libssh-0.6.0
debug1: no match: libssh-0.6.0
debug2: fd 3 setting O_NONBLOCK
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-dss
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
debug2: kex_parse_kexinit: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
debug2: kex_parse_kexinit: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-dss,ssh-rsa
debug2: kex_parse_kexinit: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,des-cbc-ssh1
debug2: kex_parse_kexinit: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,des-cbc-ssh1
debug2: kex_parse_kexinit: hmac-sha1,hmac-sha2-256,hmac-sha2-512
debug2: kex_parse_kexinit: hmac-sha1,hmac-sha2-256,hmac-sha2-512
debug2: kex_parse_kexinit: none,zlib,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: mac_setup: setup hmac-sha2-512
debug1: kex: server->client aes256-ctr hmac-sha2-512 none
debug2: mac_setup: setup hmac-sha2-512
debug1: kex: client->server aes256-ctr hmac-sha2-512 none
Unable to negotiate a key exchange method

**Comment by stribika-rdonly** [comment]
The `Host github.com` block has to come before the `Host *` block. If you configure the same options, the first one wins.

I think you have them in the wrong order:

<pre><core>debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: /etc/ssh/ssh_config line 59: Applying options for github.com</code></pre>

This part also seems to support my theory:

<pre><code>debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256</code></pre>

**Comment by AllThatIsTheCase** [comment]
Bingo, that was it! After following all of the tutorial, the keys at github will no longer be valid, so perhaps a hint to update the keys at github would be helpful for the less-initiated like me(I have that working now).
Super thanks!
